### PR TITLE
clients/lighthouse-bn: Add Optimistic Sync Options + Trusted Peers with Static Keys

### PR DESCRIPTION
**Pull request by marioevz**
Adds client support for `HIVE_ETH2_SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` setting:
- `SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` is set in `config.yaml`
- `--safe-slots-to-import-optimistically` is set as parameter to the same value

### CODE REVIEW

**Comment by marioevz** [comment]
Hi @pawanjay176, I added static keys for at least 5 nodes.
Let me know if this looks ok, thanks!

**Comment by pawanjay176** [comment]
@marioevz we are very close to merging a PR (https://github.com/sigp/lighthouse/pull/3428) which might make the `trusted-peers` hack redundant. I'm trying to test out the optimistic sync hive test cases with that PR but the tests are ending prematurely for some reason.

I'll try to fix it up locally and let you know if the static peers is indeed required.

**Comment by marioevz** [comment]
Hey @pawanjay176, I guess it wouldn't hurt to have this fix merged and then remove it in a subsequent PR if necessary.
Could we go ahead and merge since this is required for another PR (#637) ?
Thanks.

**Comment by pawanjay176** [comment]
Yep, sgtm.

**Pull request merged**
