### PR TITLE
clients: add ethereumjs

### PR DESCRIPTION
**Pull request by cbrzn**
This PR aims to add EthereumJS as a client so it can be tested against the hive. Currently, the objective is to make sure that we are good to go with the Engine API. Here is a track of what we have green so far https://hackmd.io/lKw1UArUSWu1_lOdbt3heQ?view

TODO: 
- [x]   Remove readme in merge-ethereumjs folder
- [x] Generate `version.txt` file on script

### CODE REVIEW

**Comment by fjl** [comment]
Can ethereumjs also run other tests or is this only about the engine API?

**Comment by cbrzn** [comment]
@fjl this is only about engine API - but once we are ready with it we plan to also run other tests!

**Comment by cbrzn** [comment]
Hey @fjl this is ready for review, currently, we are passing 29 of 43 tests (You can check the hackmd link in the description of the PR) and will focus on fixing the red ones. Since I don't think the initialization script will change, I would say this is good to merge

Note: Basically I forked the original hackmd (https://notes.ethereum.org/xnKiAcNlT2aZ66DdH8LM6g?view) not sure if I should modify this one once this is merged? Lmk what do you think it's the best path, and thanks for your time :pray:

**Comment by holgerd77** [comment]
Anyone able to give this a review/merge? 🙂 (we are excitedly waiting to see this in action! 😋)

**Comment by fjl** [comment]
I'm OK with merging this PR optimistically (it can't break anything), but let's call the client simply `ethereumjs`.

**Comment by holgerd77** [comment]
> I'm OK with merging this PR optimistically (it can't break anything), but let's call rename the client to simply `ethereumjs`.

Cool! 😄 👍 

Not sure if @cbrzn knows what to do, but for me it is not directly obvious: so what kind of renaming are you referring to? So the clients in the [clients](https://github.com/ethereum/hive/tree/master/clients) directly have the merge related tests also placed in `merge-*` folders - e.g. `merge-nethermind - so I guess you do not refer to renaming that (or do you)?

Is there another client naming reference in the code base?

**Comment by cbrzn** [comment]
> > I'm OK with merging this PR optimistically (it can't break anything), but let's call rename the client to simply `ethereumjs`.
> 
> Cool! smile +1
> 
> Not sure if @cbrzn knows what to do, but for me it is not directly obvious: so what kind of renaming are you referring to? So the clients in the [clients](https://github.com/ethereum/hive/tree/master/clients) directly have the merge related tests also placed in `merge-*` folders - e.g. `merge-nethermind` - so I guess you do not refer to renaming that (or do you)?
> 
> Is there another client naming reference in the code base (couldn't find any)?

Hey @holgerd77 I missed previous comment from flj, I think what he means is to the `merge-ethereumjs` folder. Geth and Nethermind has the `merge-*` prefix because (this is just my guess) they probably use different parameters in the initialization to work with the Engine API, but currently for geth there's a PR to just have the `go-ethereum` folder.

I will do this later today :)

**Comment by holgerd77** [comment]
@cbrzn ah ok, thanks, then let's do this pre-actively. 😋 Thanks for tackling directly.

**Comment by fjl** [comment]
@holgerd77 In hive, there is a strict separation between clients and tests. The client definitions should ideally only exist once, and clients can implement various interfaces (e.g. eth1 client, beacon client, validator...).

The `merge-*` client definitions were added temporarily in order to prototype the merge tests. We will back-port the merge features into the main client defitions very soon.

**Comment by cbrzn** [comment]
We should be good to go now! Let me know if something else is needed :pray: @fjl

**Comment by holgerd77** [comment]
🎉

Very cool! 👍 😄 

Am I correct that there should now be some results showing up on https://hivetests.ethdevops.io/ from our client, or is there some (any) additional in-between steps yet to be taken? 🤔

**Comment by holgerd77** [comment]
> There are additional steps required to run it. We will include it in future runs when we will deploy the test runner next time.

Ah ok, thanks, good to know! 👍

(sorry, guess I am close to having all basic questions answered 😋 😬): once you deploy will this *then*  directly run the whole test suite (so also the non-merge tests) already?

**Comment by holgerd77** [comment]
> There are additional steps required to run it. We will include it in future runs when we will deploy the test runner next time.

Any update on this?

**Comment by holiman** [comment]
@holgerd77 which tests should we execute? I'm fine with executing all, but if the consensus tests aren't supported, we can shave off ~24 hours of executionn by simply omitting specifically that test.

**Comment by fjl** [comment]
`ethereumjs` does not support most tests because it is not a full eth1 client. AFAIK the client definition is only capable of running the `ethereum/engine` tests.

**Comment by holiman** [comment]
I added it on several tests for now,  can always disable it later

**Comment by holgerd77** [comment]
> ethereumjs does not support most tests because it is not a full eth1 client

Ah no, we are relatively close on being a "full" eth1 client - if the definition is to expose most of the JSON RPC API and being able to sync and execute blocks. We do not have some more fancy sync mechanisms yet (snap sync), but I guess that is not tested here anyhow?

So you can activate for the whole (most of the) test suite I guess.

**Comment by holgerd77** [comment]
> I added it on several tests for now, can always disable it later

Thanks! 👍 🙂 🙏

**Comment by holiman** [comment]
Sgtm!

**Comment by holgerd77** [comment]
> Sgtm!

? 🙂

This PR was merged months ago, was this a reaction to any new events or similar or does this trigger anything new?

Anyhow: all the best 👋, just a bit puzzled. 😋

**Comment by holiman** [comment]
>  just a bit puzzled. yum

So am I. I've seen this happen several times -- emails written weeks/months ago are popping in on github these last couple of days. Must have gotten stuck internally at google. 

Another example: https://github.com/ethereum/go-ethereum/pull/25822#issuecomment-1274262733

**Pull request merged**
