### PR TITLE
simulators/devp2p: updated chain file to include more tx

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**

### CODE REVIEW

**Comment by fjl** [comment]
This is the 'sync' test. You need to replace the chain of 'simulators/devp2p/eth' instead.

**Comment by MariusVanDerWijden** [comment]
Sorry :see_no_evil: fixed now

**Comment by fjl** [comment]
We also need to update halfchain.rlp

**Comment by MariusVanDerWijden** [comment]
It's already updated @fjl

**Comment by fjl** [comment]
Damn, I missed that. Sorry!

**Pull request merged**
