### PR TITLE
simulators/ethereum/engine: Test sending `engine_forkchoiceUpdatedV1`, `engine_newPayloadV1` post-shanghai

### PR DESCRIPTION
**Pull request by marioevz**
Adds a test in `simulators/ethereum/engine` to verify that sending `engine_forkchoiceUpdatedV1` or `engine_newPayloadV1` post-Shanghai results in `InvalidParams` error (-32602).

Although this is not explicitly stated in spec, it caused an issue on nimbus as geth started building a transition payload with empty withdrawals because of this.

Setting this as draft because there is nothing explicit in the spec to describe this error, but I think it should be laid out.

@mkalinin @MariusVanDerWijden

### CODE REVIEW

**Comment by mkalinin** [comment]
We would have to update all `V1` methods to make them return an error if they are called with post-Shanghai payload or payload attributes, moreover, the next fork would imply the same update for `V2` methods and so forth.

Though, we could do that I wonder if there is another approach to address this problem as if we require CL clients to use `V2` methods since Shanghai. Would we be able to test this kind of requirement in Hive?

**Comment by marioevz** [comment]
Yes, this is addressed in #712

**Comment by fjl** [comment]
@marioevz still want this in?

**Comment by marioevz** [comment]
> @marioevz still want this in?

I think this is way too outdated, will close for now.

**Pull request closed without merging**
