### PR TITLE
simulators/devp2p: enable discv5 test suite

### PR DESCRIPTION
**Pull request by fjl**
This adds support for running the discv5 test suite from go-ethereum's cmd/devp2p against EL and CL clients.

### CODE REVIEW

**Comment by holgerd77** [comment]
For context: is this more/only for CL clients? EL clients are not supposed to support discv5 in any way, or do they? 🤔

**Comment by fjl** [comment]
It's not mandatory, but we're definitely moving in the direction of it being required.

**Comment by holgerd77** [comment]
Oh, that's interesting to hear. 🤯 Is there already an option to run Go Ethereum with discV5? And does it work if one does (on mainnet, e.g.)?

**Comment by fjl** [comment]
The option is there, but it isn't enabled for peer discovery. We do want to make that work though.

**Comment by holgerd77** [comment]
Would this be a topic for next ACD-E call (or P2P breakout) what your guys' ideas or rough plans are for this? Or is this still too early?

**Pull request merged**
