### PR TITLE
add portal clients and simulators

### PR DESCRIPTION
**Pull request by KolbyML**
@fjl ok here is a branch with portal clients/sims.  ``hivesim-rs`` should be a lot more stable now with <https://github.com/ethereum/portal-hive/pull/111> my latest changes (just for information). But hivesim-rs isn't in this PR as per request.

There isn't a portal branch yet and I don't have perms to make one so I will just base it off master.

I tested the simulators locally and they ran as expected

### CODE REVIEW

**Comment by KolbyML** [comment]
This PR is out of date. When felix or someone wants to get this in at me or dm me and I will spin up a up to date PR.

**Comment by fjl** [comment]
Hey, sorry for the delay here! I did give it a run but then didn't follow up. The file structure is good and client definitions look fine to me. I noticed the simulator basically syncs with the mainnet? There doesn't appear to be a fully isolated test for portal. That would be one of the things made possible by integrating with main hive, being able to run a test where portal network pulls data from a synthetic testnet within hive.

**Comment by KolbyML** [comment]
All of the tests are isolated from  our portal mainnet. All the data used on portal is from the Ethereum Mainnet. And once we are added we can write tests using EL clients as providers for our bridge which will be super cool.

Do you want me to update the PR with the lastest changes of the project, and a change to ci to only run our rust ci on prs that change our rust code?

**Comment by fjl** [comment]
If it's not too hard, it would be nice if you could commit the recent updates here.

**Comment by KolbyML** [comment]
Ok I pushed the latest updates.
The latest update doesn't include the CI change I mentioned above. As we don't have that on portal-hive either. It is a feature I do want to add for ethereum/hive
I will make a follow up PR with that after this one is merged. Since path filtering isn't as easy on circleci as it is on github-action. So I think a seperate PR would minimize review complexity.

**Comment by KolbyML** [comment]
Felix when do you expect to be able to merge this?

**Comment by KolbyML** [comment]
Closing this since it is out of date again. I am going to switch to opening smaller PR's for chunks of functionality

**Pull request closed without merging**
