### PR TITLE
clients/besu: add Shanghai fork and fix issue with duplicated node keys

### PR DESCRIPTION
**Pull request by gfukushima**
This fixes the tests where hive spins up a second instance of besu and sync from the bootnode. Currently node 1 and 2 have the same enode address which stops them from peering with each other 

Linked to [#4747](https://github.com/hyperledger/besu/issues/4747)

### CODE REVIEW

**Comment by fjl** [comment]
Is the nodekey deterministic in besu?

**Comment by gfukushima** [comment]
If you place a key in the data directory besu will read that and use it to generate the node id. If you use the same key for the bootnode and node 2 (usually used in hive to test the sync) they will have the same node address and node id. Which eventually will prevent these nodes from peering with each other.
https://besu.hyperledger.org/en/stable/public-networks/concepts/node-keys/#node-public-key

**Comment by fjl** [comment]
I understand. AFAIK, hive does not place a key in the data directory, and besu should generate a random key by itself.
If hive configures the same node key for all instances, that's a bug we should fix.

**Comment by gfukushima** [comment]
@fjl my understanding is that this is exactly what this line is doing 
https://github.com/ethereum/hive/blob/6152200ada55a957f95955351738453b4101b6d8/clients/besu/besu.sh#L109

**Comment by gfukushima** [comment]
@fjl  is there anything this PR is missing to be accepted? Right now everyone who runs the hive withdrawals suite need to add those changes manually for Besu

**Comment by fjl** [comment]
Sorry, I just wanted to confirm why the nodekey is used in clique mining mode. But it seems this is not easy to fix in besu, so we can apply this workaround for now.

**Pull request merged**
