### PR TITLE
hive: add --sim.buildarg flag

### PR DESCRIPTION
**Pull request by marioevz**
Adds `--sim.buildarg` as a parameter to add build arguments to the simulator Dockerfile.

### CODE REVIEW

**Comment by marioevz** [comment]
@spencer-tb @danceratopz

**Comment by KolbyML** [comment]
> This change will allow us to specify the "test fixture" release version used in the ethereum/execution-spec-test simulators on the command-line, just as we already specify the client version under test. Just wanted to share: perhaps it's useful for the Portal simulators?

I would find this ability useful, since I want/plan to be able to sub in testnet test data for our `portal` simulators.

**Review by spencer-tb — APPROVED** [review]
LGTM! Just tried this out and it works well.

I created a PR on top of this to update the consume dockerfiles: #1180

**Comment by fjl** [comment]
I pushed a small update before merging. The update is about using `map[string]string` instead of `[]docker.BuildArg` as the internal representation of build args. I did this because the packages `internal/libhive`, `internal/fakes` should not depend on `go-dockerclient` directly. They should only use this package via an interface.

**Pull request merged**
