### PR TITLE
clients/besu: update config to address rpc and send-legacy-transaction rpc-compat failure

### PR DESCRIPTION
**Pull request by mark-terry**
Signed-off-by: mark-terry <mark.terry@consensys.net>

### CODE REVIEW

**Comment by fjl** [comment]
Thanks for finding the fix. I think we should not add a new environment variable for this option, and instead simply set this flag for besu unconditionally.

**Comment by mark-terry** [comment]
> Thanks for finding the fix. I think we should not add a new environment variable for this option, and instead simply set this flag for besu unconditionally.

My only hesitation with that approach is that it'll prevent testing any base-fee related behaviour; which didn't seem to be a concern with rpc-compat, but might be relevant in other simulations. Any feedback on that?

**Comment by fjl** [comment]
I'm just wondering how the RPC tests can pass in other clients with no extra configuration. Could you explain a little bit what this flag does?

**Comment by mark-terry** [comment]
> I'm just wondering how the RPC tests can pass in other clients with no extra configuration. Could you explain a little bit what this flag does in besu?

Certainly. These params were updated:

- `--min-gas-price=1` - the transaction in the simulation has a `gasPrice` of 1, so the previous `min-gas-price=16` value was causing the transaction to be rejected.
- `--tx-pool-limit-by-account-percentage=1"`- this option increases the number of transactions permitted in the transaction pool from a single sender; which is appropriate for a test suite.

Genesis config:
`zeroBaseFee` - this option configures free gas on networks with London+ forks and removes the 7 wei base fee; which is higher than the transaction's `gasPrice`.

**Comment by mark-terry** [comment]
@fjl Were you waiting on anything from my side?

**Comment by fjl** [comment]
Sorry, I was on vacation and didn't get to merge it before that.

**Comment by fjl** [comment]
I have resolved the issue with baseFee being too low by updating the tests instead: https://github.com/ethereum/execution-apis/pull/347

**Comment by fjl** [comment]
I will merge this now. The legacy tx test will start passing when tests are updated upstream.

**Pull request merged**
